### ISSUE TITLE
Getting this issue when making running develop

### ISSUE THREAD

**Issue by talmax1124** [algolia/gatsby-plugin-algolia#125]
```
 throw new Error(`${`Can not convert field '${tc.getTypeName()}.${fieldName}' to ObjectType` + '\nIt should be ObjectType or InterfaceType,
but got \n'}${(0, _misc.inspect)(fc.type)}`);
        ^

Error: Can not convert field 'GatsbyPlugin.options' to ObjectType
It should be ObjectType or InterfaceType, but got
ThunkComposer({ _thunk: [function ], _typeFromThunk: undefined })
    at /Users/carlitos/Documents/Neocity/KTBLOG3/node_modules/gatsby-cli/node_modules/graphql-compose/lib/utils/toInputType.js:100:15
    at Array.forEach (<anonymous>)
    at toInputObjectType
(/Users/carlitos/Documents/Neocity/KTBLOG3/node_modules/gatsby-cli/node_modules/graphql-compose/lib/utils/toInputType.js:89:14)
    at ObjectTypeComposer.getInputTypeComposer
(/Users/carlitos/Documents/Neocity/KTBLOG3/node_modules/gatsby-cli/node_modules/graphql-compose/lib/ObjectTypeComposer.js:909:71)
    at ObjectTypeComposer.getInputType
(/Users/carlitos/Documents/Neocity/KTBLOG3/node_modules/gatsby-cli/node_modules/graphql-compose/lib/ObjectTypeComposer.js:895:17)
    at /Users/carlitos/Documents/Neocity/KTBLOG3/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphql-server/server.js:25332:101
    at Array.map (<anonymous>)
    at createTypes
(/Users/carlitos/Documents/Neocity/KTBLOG3/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphql-server/server.js:25277:51)
    at Object.<anonymous>
(/Users/carlitos/Documents/Neocity/KTBLOG3/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphql-server/server.js:25508:5)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
```

**Comment by Haroenv** [comment]
Do you have this in a GitHub repository that I can try?

**Comment by Haroenv** [comment]
I don't think this is related to the current plugin, but if it is, please post a reproduction, thanks!
